sudo: true
language: c

addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - gcc-6
        - g++-6
        - indent
        - cppcheck
        - kwstyle

os:
  - linux

script:
  - pwd
  - ruby --version
  - gem install --pre bam-bam-boogieman
