sudo: true
language: c

addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
     packages:
        - gcc-6
        - g++-6
        - indent
        - cppcheck
        - kwstyle
        - mono-complete

os:
  - linux

script:
  - pwd
  - ruby --version
  - mono --version
  - wget --no-verbose --method=GET -qO - http://llvm-apt.ecranbleu.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
#  - .travis/install_smack.sh
#  - ls 
#  - gem install --pre bam-bam-boogieman
  
