sudo: true
language: c

addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - gcc-6
        - g++-6
        - indent
        - cppcheck
        - kwstyle
	- mono-complete

os:
  - linux

script:
  - pwd
  - ruby --version
  - mono --version
  - .travis/install_smack.sh
  - ls 
  - gem install --pre bam-bam-boogieman
  
