sudo: required
dist: trusty
language: c

addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - gcc-6
        - g++-6
        - indent
        - cppcheck
        - kwstyle

os:
  - linux

script:
  - sudo apt-get purge -y cpp-6 g++-6 gcc-6 gcc-6-base libgcc-6-dev libstdc++-6-dev
  - gcc --version
  - ruby --version
  - .travis/install_smack.sh
  - mono --version
  - gem install --pre bam-bam-boogieman
  
