sudo: required
dist: trusty
language: c

addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - gcc-6
        - g++-6
        - indent
        - cppcheck
        - kwstyle

os:
  - linux

script:
  - pwd
  - ruby --version
  - .travis/install_smack.sh
  - mono --version
  - gem install --pre bam-bam-boogieman
  
