sudo: required
dist: trusty
language: c

addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - indent
        - cppcheck
        - kwstyle

os:
  - linux

script:
  - pwd
  
