sudo: true
language: c

addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - gcc-6
        - g++-6
        - indent
        - cppcheck
        - kwstyle
        - mono-complete

os:
  - linux

script:
  - wget --no-verbose  google.com; wget --method=GET google.com