include ../../lib/ct-verif.mk

#goals += s2n_constant_time_equals@ctequals.c
#goals += dummy@ctequals.c
#goals += foo@clequals.c
#goals += foo1@clequals.c
#goals += foo2@clequals.c
#goals += foo3@clequals.c
#goals += foo4@clequals.c
#goals += foo5@clequals.c
#goals += foo5_1@clequals.c
#goals += foo6@clequals.c
goals += foo6_1@clequals.c
#goals += foo7@clequals.c
#goals += foo8@clequals.c
#goals += foo9@clequals.c
#goals += foo10@clequals.c

timing += true
